name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 1"
jobs:
  test:
    env:
      POSTGRESQL: 18
      TARGET_PROJECT_NAME: myproj
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run rename script               # removed by rename.sh
        run: ./rename.sh $TARGET_PROJECT_NAME # removed by rename.sh
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-03-10
          components: rustfmt,llvm-tools-preview,clippy
      - uses: Swatinem/rust-cache@v2
      - uses: taiki-e/install-action@cargo-hack
      - name: Set up PostgreSQL
        run: |
          sudo systemctl stop postgresql
          sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh -y
          sudo apt install postgresql-$POSTGRESQL
          sudo pg_createcluster $POSTGRESQL main
          sudo sed -i -e 's|5433|5432|' /etc/postgresql/$POSTGRESQL/main/postgresql.conf
          sudo sed -i -e '/^local/ s|peer|trust|' /etc/postgresql/$POSTGRESQL/main/pg_hba.conf
          sudo pg_ctlcluster $POSTGRESQL main start
      - name: Init the database
        run: |
          psql --username postgres -c "CREATE DATABASE $TARGET_PROJECT_NAME"
          psql --username postgres -c "CREATE USER $TARGET_PROJECT_NAME WITH PASSWORD '$TARGET_PROJECT_NAME'"
          psql --username postgres -c "GRANT ALL ON DATABASE $TARGET_PROJECT_NAME TO $TARGET_PROJECT_NAME"
      #- name: Save rust version for proper cache setup
      #  run: rustc -V > .rustc.version
      #- uses: actions/cache@v5
      #  with:
      #    path: |
      #      ~/.cargo/bin/
      #      ~/.cargo/registry/index/
      #      ~/.cargo/registry/cache/
      #      ~/.cargo/git/db/
      #    key: cargo-${{ hashFiles('**/Cargo.lock') }}
      #    restore-keys: cargo-
      #- uses: actions/cache@v5
      #  with:
      #    path: |
      #      target/
      #    key: ${{ runner.os }}-target-${{ hashFiles('.rustc.version') }}-${{ hashFiles('**/Cargo.lock') }}
      #    restore-keys: ${{ runner.os }}-target-${{ hashFiles('.rustc.version') }}-
      - name: Format check
        run: cargo fmt --check
      - name: Clippy check
        run: cargo clippy --all-targets
        env:
          CARGO_TARGET_DIR: target/clippy  # avoid overwriting normal build artifacts
      - name: Build as workspace
        run: cargo build
      - name: Build as individual crates
        run: cargo hack --workspace build
      - name: Test
        run: cargo test
        env:
          DATABASE_URL: postgres:///?user=postgres
      - name: Run the daemon
        run: |
          timeout 2s cargo run --bin $TARGET_PROJECT_NAME-daemon -- --dsn postgresql://$TARGET_PROJECT_NAME:$TARGET_PROJECT_NAME@localhost/$TARGET_PROJECT_NAME || err=$?
          if [ $err -eq 124 ]; then exit 0; else exit $err; fi  # timeout is OK, it means that the daemon has started
      - name: Run the webapp
        run: |
          timeout 2s cargo run --bin $TARGET_PROJECT_NAME-web -- --dsn postgresql://$TARGET_PROJECT_NAME:$TARGET_PROJECT_NAME@localhost/$TARGET_PROJECT_NAME --listen 127.0.0.1:3000 || err=$?
          if [ $err -eq 124 ]; then exit 0; else exit $err; fi  # timeout is OK, it means that the daemon has started
